### ISSUE TITLE
Highlighting of phrase box contents

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#101]
When the phrase box is moved to a new location, either by hitting the Enter key, or when manually placing it to a particular location, the contents of the phrase box should automatically be highlighted, so that when the user begins to type something, the first letter typed will replace the contents of the phrase box (this would imitate the behavior of the AID app). Otherwise, I find that most of my time is taken up fiddling with trying to get the existing content of the box removed, either by attempting to highlight the whole content with a long press on the box (impossible except for long source words), or by placing the edit cursor within the box contents and getting its content ready to accept what I want to type there. With my big fingers, touching the edit box never seems to get the edit cursor placed where I want it at the end of the word (and there are no arrow keys) - necessitating more fiddles to get the cursor in the right place to be able to use the backspace button to remove what I don't want in the edit box - there is no equivalent on my Android keyboard of the Delete key on a regular keyboard. If the phrase box would automatically highlight its contents when it moves (or is moved/placed manually), that would dramatically make the editing process much simpler on touch screens

**Comment by adaptitbruce** [comment]
Hi guys,

Since there are no arrow keys and no delete button, what about turning the phrasebox into a suite of controls. Perhaps arrow buttons at either end to move the cursor left or right, and a delete button maybe to the left of the lefthand arrow key. Those 3 buttons would be constrained to go wherever the phrasebox goes and stay close no matter what. Seems sort of like a very Christian idea :-)

--Bruce

On a serious note, the editing experience for the user needs to be top quality. If there is difficulty or frustration, it will be there every minute, every hour, every day, and turn people off. 
  ----- Original Message ----- 
  From: Bill Martin 
  To: adapt-it/adapt-it-mobile 
  Sent: Thursday, September 03, 2015 4:08 AM
  Subject: [adapt-it-mobile] Highlighting of phrase box contents (#101)


  When the phrase box is moved to a new location, either by hitting the Enter key, or when manually placing it to a particular location, the contents of the phrase box should automatically be highlighted, so that when the user begins to type something, the first letter typed will replace the contents of the phrase box (this would imitate the behavior of the AID app). Otherwise, I find that most of my time is taken up fiddling with trying to get the existing content of the box removed, either by attempting to highlight the whole content with a long press on the box (impossible except for long source words), or by placing the edit cursor within the box contents and getting its content ready to accept what I want to type there. With my big fingers, touching the edit box never seems to get the edit cursor placed where I want it at the end of the word (and there are no arrow keys) - necessitating more fiddles to get the cursor in the right place to be able to use the backspace bu tton to remove what I don't want in the edit box - there is no equivalent on my Android keyboard of the Delete key on a regular keyboard. If the phrase box would automatically highlight its contents when it moves (or is moved/placed manually), that would dramatically make the editing process much simpler on touch screens
