### ISSUE TITLE
Overriding Android keyboard auto-caps behavior

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#102]
Can AIM control certain settings for text input, such as automatic capitalization? It would be very desirable if the AIM Android app could turn off the default capitalization of the built in virtual Android keyboard. As it is now in its default state, AIM wants to capitalize every word or phrase that gets adapted (it automatically shifts to the upper case key set probably because it assumes every edit box is at the beginning of a new sentence!). Hence, I find I have to go back and re-adapt a lot just to change capitalized words to begin with a lower case letter - which necessitates fiddling with the cursor insert point, pressing backspace, pressing on the SHIFT key to get the lower case letter set displaying before typing the actual lower case key. It would be nice to know if this auto caps behavior of Android phones can be shut off and capitalization be controlled just by AIM, at least while the running AIM app is in focus.

**Comment by kanaka** [comment]
I think this is just an attribute on the input box: http://www.bennadel.com/blog/2307-disabling-auto-correct-and-auto-capitalize-features-on-iphone-inputs.htm

If that can't be made to work reliably, there is always the option of detecting keys as they are input and changing them on-the-fly to match the capitalization of the source text or something like that.

**Comment by adaptitbruce** [comment]
Yes indeed! --Bruce
  ----- Original Message ----- 
  From: Bill Martin 
  To: adapt-it/adapt-it-mobile 
  Sent: Thursday, September 03, 2015 4:09 AM
  Subject: [adapt-it-mobile] Overriding Android keyboard auto-caps behavior (#102)


  Can AIM control certain settings for text input, such as automatic capitalization? It would be very desirable if the AIM Android app could turn off the default capitalization of the built in virtual Android keyboard. As it is now in its default state, AIM wants to capitalize every word or phrase that gets adapted (it automatically shifts to the upper case key set probably because it assumes every edit box is at the beginning of a new sentence!). Hence, I find I have to go back and re-adapt a lot just to change capitalized words to begin with a lower case letter - which necessitates fiddling with the cursor insert point, pressing backspace, pressing on the SHIFT key to get the lower case letter set displaying before typing the actual lower case key. It would be nice to know if this auto caps behavior of Android phones can be shut off and capitalization be controlled just by AIM, at least while the running AIM app is in focus.

**Comment by eb1** [comment]
@kanaka - it looks like the autocapitalize attribute is iOS only, and available on `<input>` elements (we use contenteditable `<div>` elements): https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input. Bummer!

I'm also a little reluctant to do keystroke correction, as AIM wouldn't know when the source justifiably differs from the target in terms of capitalization. 

I'm going to punt on this issue for now. If we come across some way to programmatically turn off the auto-caps -- either in the API or Android Manifest -- that would be fantastic. But right now it seems like the safest way to address this issue is to have the user manually turn off auto-caps in the Android preferences.

**Comment by kanaka** [comment]
@eb1 I see. I didn't realize we were using contenteditable. When I made the old [proof-of-concept](https://github.com/kanaka/adaptit-html5-poc), I researched contenteditable vs input areas and there seemed to be a rough consensus that contenteditable had a lot of issues (especially on mobile) so I ended up using plain input areas. Maybe contenteditable has improved since then. If I were starting the interface from scratch, I would strongly consider something like [prosemirror](https://github.com/prosemirror/prosemirror) ([intro](http://marijnhaverbeke.nl/blog/prosemirror.html)) which leverages contenteditable for it's strengths (focus and cursor motion) but works around it's weaknesses in other areas. In addition, prosemirror is built from the ground up to support simultaneous collaborative editing which certainly seems interesting in this context. Not suggesting AIM should switch, but looking at how prosemirror uses contenteditable might be useful.

**Comment by eb1** [comment]
Looks like we might have a fix for this -- moving to milestone 1.9.0.

**Comment by eb1** [comment]
Fix added in https://github.com/eb1/adapt-it-mobile/commit/1b63aa9f3eba49a844cbce8705342fd3b63e0afb (adding `autocapitalize=off` to target and gloss edit fields, as these are now supported as a global attribute for both iOS and Android browsers). Tested on iOS 16 / Android 10.

**Comment by GraeCost** [comment]
Good on you, Erik.

All the best,
Graeme
