### ISSUE TITLE
AIM not jumping to next hole

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#104]
AIM seems to only support what in AID is called the "Review" mode, and not "Drafting" mode. AIM currently seems to only move the phrase box to the immediately following source word, rather than skipping to the next "hole". That is, when Enter is pressed in AID's default "Drafting" mode, AID will jump over all immediately following existing adaptations to the next un-adapted location or "hole" and stop there. For a more efficient user experience, AIM should also support the "Drafting" mode as the default mode.

**Comment by adaptitbruce** [comment]
Yes, AID does this by examining the m_bHasKBEntry and m_bNotInKB and m_bRetranslation  flags on the sequence of CSourcePhrases which lie ahead; (maybe others - I'm going from memory) and when these are all FALSE, it knows it has come to a hole. It isn't enough to look for an empty adaptation, because sometimes an empty string is a valid adaptation of a certain source text word in a certain context (in fact, finding a hole by means of a lack of an adaptation is linguistically and translationally dangerous). But then, I haven't looked at AIM to see how it is done, so maybe I'm out of line. I don't know how many boolean flags AIM maintains in its sourcephrase; AID maintains 22, and last year sometime I worked out that AIM would need at least 9, and better still, 11, if it was to offer functionality similar to AID. A *lot* of AID's editing smarts are provided by use of various flags; without them, more work has to be done by the user. Some important flags are on the app class. For instance, m_bUserTypedSomething. This is false by default, until the user types in the phrasebox, or at least clicks in it, either of which turn it true. It's important when the phrasebox lands somewhere because of some action by the user, and then he decides to locate the phrasebox elsewhere - if at that last step that flag is still false, then the string copied to the phrasebox when it landed at the intermediate location is thrown away. Otherwise, it remains in the phrasebox and the subsequent movement of the box to another location causes what would be a bogus adaptation to get added to the KB. So I think a lot of attention needs to be given to the support of common user actions so that when they are done, they don't cause lots of "oh, I didn't mean that to happen, darn, now I have to get rid of .... and clean up the KB because of....".

--Bruce
  ----- Original Message ----- 
  From: Bill Martin 
  To: adapt-it/adapt-it-mobile 
  Sent: Thursday, September 03, 2015 5:23 AM
  Subject: [adapt-it-mobile] AIM not jumping to next hole (#104)


  AIM seems to only support what in AID is called the "Review" mode, and not "Drafting" mode. AIM currently seems to only move the phrase box to the immediately following source word, rather than skipping to the next "hole". That is, when Enter is pressed in AID's default "Drafting" mode, AID will jump over all immediately following existing adaptations to the next un-adapted location or "hole" and stop there. For a more efficient user experience, AIM should also support the "Drafting" mode as the default mode.
