### ISSUE TITLE
Adapt screen: wacky,,, punctuation....

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#107]
When tabbing multiple times through piles that have punctuation, the punctuation marks get added to those piles -- multiple times. I'm not sure of the pattern yet, but it looks like it affects all target sourcephrases with punctuation.

**Comment by adaptitbruce** [comment]
Hi Erik

I'm wondering if, when the phrasebox lands at a location, you are populuting it with the punctuation-added target text, rather than the punctuation-less target text as AID does. Because if punctuation is added when the box moves, it will add itself to punctuation already present. AID gives the user the punctuation-less tgt text, so that when the box moves, the punctuation gets added back, and doesn't double up.

--Bruce
  ----- Original Message ----- 
  From: Erik Brommers 
  To: adapt-it/adapt-it-mobile 
  Sent: Wednesday, September 09, 2015 1:42 AM
  Subject: [adapt-it-mobile] Adapt screen: wacky,,, punctuation.... (#107)


  When tabbing multiple times through piles that have punctuation, the punctuation marks get added to those piles -- multiple times. I'm not sure of the pattern yet, but it looks like it affects all target sourcephrases with punctuation.
