### ISSUE TITLE
Select phrase, start typing --> merge the phrase

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#109]
Adapt It desktop has a feature that allows users to automatically merge the selection into a single phrase by doing the following:
1. Select several piles
2. Start typing

It would be nice to incorporate this feature into AIM, so that users don't have to click a button (merge phrase) to merge the phrase and then re-select the phrase to edit the target text.

**Comment by pngbill** [comment]
When the selection is made, and the user starts to type, several things should happen at the point that the first keypress on the keyboard happens: 1) The source phrase piles are merged together so that a single target cell exists under the merged phrase, 2) The phrasebox is located in the target line under the whole merged source phrase, 4) The phrasebox will be emptied before the first keystroke is entered into that phrasebox, so that what the user is typing will form the new next target cell text within the phrasebox. This "automatic merging upon typing" action contrasts slightly from what should happen if the user selects two or more source words, and hits the Merge a Phrase button (before typing anything). In this merge by button press case, these things should happen: 1) Any existing target text content of the individual piles being merged, should be temporarily saved and concatenated together with intervening spaces, 2) The source phrase piles are merged together so that a single target cell exists under the merged phrase, 3) The phrasebox is located in the target line under the whole merged source phrase, 4) The concatenated target text that was temporarily stored, should be placed in the phrasebox, and 5) The whole text in the target cell should be highlighted, with the keyboard presented and ready for the user to either start typing a replacement text or edit the text as is. If the user decides it would be faster to edit the existing highlighted text rather than doing a total replacement of the selected target text, s/he can manually tap on the target cell with a finger to cause that cell to lose its highlighting and get the edit cursor placed for a modification of the existing target text, rather than a wholesale replacement that would be done via the typing action.

**Comment by adaptitbruce** [comment]
On 11/09/2015 9:16 AM, Bill Martin wrote:
>
> When the selection is made, and the user starts to type, several
> things should happen at the point that the first keypress on the
> keyboard happens: 1) The source phrase piles are merged together so
> that a single target cell exists under the merged phrase, 2) The
> phrasebox is located in the target line under the whole merged source
> phrase, 4) The phrasebox will be emptied before the first keystroke is
> entered into that phrasebox, so that what the user is typing will form
> the new next target cell text within the phrasebox. This "automatic
> merging upon typing" action contrasts slightly from what should happen
> if the user selects two or more source words, and hits the Merge a
> Phrase button (before typing anything). In this merge by button press
> case, these things should happen: 1) Any existing target text content
> of the individual piles being merged, should be temporarily saved and
> concatenated together with intervening spaces, 2) The source phrase
> piles are merged together so that a single target cell exists under
> the merged phrase, 3) The phrasebox is located in the target line
> under the whole merged source phrase, 4) The concatenated target text
> that was temporarily stored, should be placed in the phrasebox, and 5)
> The whole text in the target cell should be highlighted, with the
> keyboard presented and ready for the user to either start typing a
> replacement text or edit the text as is. If the user decides it would
> be faster to edit the existing highlighted text rather than doing a
> total replacement of the selected target text, s/he can manually tap
> on the target cell with a finger to cause that cell to lose its
> highlighting and get the edit cursor placed for a modification of the
> existing target text, rather than a wholesale replacement that would
> be done via the typing action.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adapt-it/adapt-it-mobile/issues/109#issuecomment-139409013>.
>
Sounds pretty right. --Bruce

**Comment by eb1** [comment]
Moving this defect to 1.0 beta:

Selecting the first target word after a selected phrase is causing different behavior between browser operating systems. I'm punting on this until a more consistent initial selection algorithm can be determined.

**Comment by eb1** [comment]
Moving this out to the 1.0 release candidate milestone.

**Comment by eb1** [comment]
Moving this to release 1.17.0.
