### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by pngbill** [adapt-it/adapt-it-mobile#120]
After adapting a few verses, I find that that I have to manually scroll the screen to see the word/phrase that I want to adapt. But that manual scrolling results in problems keeping the phrasebox at the desired location. With several strips of text already adapted above, I tap under the source text where I want to enter a target equivalent, but when the keyboard appears it covers the strip where I am translating, and often when this happens, I will want to see where I am translating, so I manually scroll the text up (by dragging an area of it up) to see where I am translating. I get the phrasebox comes into view (if I have not accidentally made it go elsewhere touching the screen during manual scrolling). I then tap phrasebox under the adaptation point to get the insertion point into the box and/or to get the keyboard to appear. Often, just before AIM brings up the keyboard it seems to scroll back towards the beginning of the document, then scroll down even further that its original point, then when it brings up the keyboard, AIM then moves the phrasebox focus to a location several strips above where I was working, instead of where I had tapped. This seems to mainly happen after I have manually scrolled to view the translation point. There seem to be two problems here. 1) The strip being translated doesn't scroll into view as it should when the keyboard appears, and/or 2) After manually scrolling down in the document and tapping the desired adaptation location, AIM sometimes (in the process of bringing up the keyboard?) moves the phrasebox to a different location than the location where I just tapped to insert an adaptation. This happened on my 7" tablet held in portrait orientation. It was showing about 10 strips of adapted text (without the keyboard showing).

**Comment by adaptitbruce** [comment]
I dunno if this is relevant, but the way AID keeps track is to locate the active location where the user action took place, in the list of strips and their piles (it doesn't matter if it is a strip out), and then use that area of the layout (taking enough strips before so that the start point for drawing is above the top of the screen, and enough below the screen so that pile flow-up, which produces strips with m_bValid set FALSE, doesn't produce any invalid strips in the visible area of the screen below the remembered active strip. Any strip which needs pile flowup is marked m_bValid FALSE, and the code does the flowup and handling of the phrase box location, leaving any just-produced m_bValid FALSE strips off screen, so the drawing of those doesn't matter. Sometimes pile flowup empties a strip, and so there's code to remove a strip when needed.

--Bruce
  ----- Original Message ----- 
  From: Bill Martin 
  To: adapt-it/adapt-it-mobile 
  Sent: Wednesday, November 04, 2015 7:53 AM
  Subject: [adapt-it-mobile] Scrolling problem (#120)


  After adapting a few verses, I find that that I have to manually scroll the screen to see the word/phrase that I want to adapt. But that manual scrolling results in problems keeping the phrasebox at the desired location. With several strips of text already adapted above, I tap under the source text where I want to enter a target equivalent, but when the keyboard appears it covers the strip where I am translating, and often when this happens, I will want to see where I am translating, so I manually scroll the text up (by dragging an area of it up) to see where I am translating. I get the phrasebox comes into view (if I have not accidentally made it go elsewhere touching the screen during manual scrolling). I then tap phrasebox under the adaptation point to get the insertion point into the box and/or to get the keyboard to appear. Often, just before AIM brings up the keyboard it seems to scroll back towards the beginning of the document, then scroll down even further that it s origin al point, then when it brings up the keyboard, AIM then moves the phrasebox focus to a location several strips above where I was working, instead of where I had tapped. This seems to mainly happen after I have manually scrolled to view the translation point. There seem to be two problems here. 1) The strip being translated doesn't scroll into view as it should when the keyboard appears, and/or 2) After manually scrolling down in the document and tapping the desired adaptation location, AIM sometimes (in the process of bringing up the keyboard?) moves the phrasebox to a different location than the location where I just tapped to insert an adaptation. This happened on my 7" tablet held in portrait orientation. It was showing about 10 strips of adapted text (without the keyboard showing).

**Comment by eb1** [comment]
Made a couple changes in order to address this "over-eager" scrolling issue:

1. AIM now only scrolls the text into view if the item is directly next to the previous selection; that is, if the user has likely selected the Previous or Next buttons. In this particular case, the KB suggestions might have moved the active edit field offscreen. If the user has selected an item that is not directly next to the previous selection, the assumption is that the user can see the edit field (they clicked it, after all), and no scrolling is done.

2. Scrolling is done to the top of the parent element, not to the bottom. In other words, the edit field is scrolled so that the item is just below the toolbar, instead of at the bottom of the screen. This should allow room for the soft keyboard to display and still show the edit field.

**Comment by pngbill** [comment]
I think this issue needs reopening. The scrolling, I think needs to be smarter. This is especially true since AIM will be available on a broad range of screen sizes (including 10" tablets that have a bluetooth keyboard). The algorithm needs to be aware of how many "strips" are possible to display on the screen as a whole and especially how many can be displayed above the popup keyboard. The current algorithm is OK if there is only room for one strip above the keyboard (where the edit box is located). However, I think the algorithm should not always scroll the strip which has the active edit box up to "just below the toolbar", because this results in a previous strip of the translation being scrolled up and not visible, making the entire preceding context become invisible, and making it necessary for the user to scroll back to see that previous strip/context. If screen space is available (when the keyboard is showing), the algorithm should try to display at least one strip of text above the current strip where the active edit box is located. I've been testing AIM on a desktop monitor because I've not figured out how to get a freshly compiled .apk file over to my phone or small tablet. And, with AIM running on the desktop monitor there is room for at least 12 strips (a tablet held in portrait orientation would probably have at least 10 strips without the keyboard showing, and 6-7 strips even with a keyboard showing. Except for small screen smart phones, it should be possible for the user to see at least one full strip of translated text above the current strip being translated. Being able to see some context of previously translated text is important - more so than being able to see a lot of following (untranslated) source text.

**Comment by eb1** [comment]
Re-closing this issue:

The reopening request requires a fair amount of work, as there is no javascript call to scroll the window into the area desired. Since there was already work done for the 0.5.0 milestone, I've created another issue (issue #128) to track this new work.

**Comment by kanaka** [comment]
It might be difficult to calculate what the proper location is, but you can scroll with javascript to an arbitrary position or element (div) on the page. For example: 
* http://stackoverflow.com/questions/15158937/jquery-jump-or-scroll-to-certain-position-div-or-target-on-the-page-from-button
* http://jsfiddle.net/lollero/ZVdRt/262/

**Comment by eb1** [comment]
@kanaka Thanks, I'll add that to the other issue.

**Comment by adaptitbruce** [comment]
Hi Erik,
Yes, Bill is right about this. Being able to see what has been adapted prior to the current location of the phrasebox is one of the most important things about the whole adaptation process.  It's great to see how the interface is improving. If you think that we can soon put out an alpha to a wider audience than just our team (actually, just Bill and Kevin at the moment, I've not had time to follow your stuff), let's talk about it at year's end - after Christmas sometime.

--Bruce
  ----- Original Message -----
