### ISSUE TITLE
Milestone 0.5.0 upgrade: "App not installed"

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#130]
Per Bill:

"I just downloaded AIM alpha 0.5.0 and attempted to install 0.5.0 while 0.4.5 was installed. My android Samsung 7" tablet (Android 4.4.2) went through the motions of installing, but at the end it said, 
X App not installed
I verified that no newer version was installed by going to the program manager.
I tried this several times but with the same message. So, in the program manager I selected Adapt It Mobile (the 0.4.5 version), and clicked on "Uninstall" (I didn't touch the "Clear" buttons). It uninstalled 0.4.5. Then I went back to my Downloads folder, and double clicked on the 0.5.0 version's apk file I had just downloaded. It installed 0.5.0 OK, but running the application, it removed all of my previous data :(. Something is preventing the installation of a newer version of AIM on Android. It seems that the only way to do so is to first uninstall the previous version of AIM which, unfortunately destroys all project data - even though no action was taken to clear any data or cache. I have camera generated screen shots of the whole process available if you want to see them."

**Comment by eb1** [comment]
Reference the reopening comments from #112.

**Comment by eb1** [comment]
@pngbill - if you could attach screen shots of the process, that would be really helpful. Also, were both versions of the app release ones from the PG build site, or debug ones created on your machine?

**Comment by pngbill** [comment]
I'll try to attach the jpg images here after this comment. I took them with my camera of the tablet screen since I've not tried to get screen shots on any Android device before (I suppose there is an app for that). I pretty sure that both the version 0.4.5 I was trying to replace and the version 0.5.0 were app release versions from the PG build site (they had "release" as part of the apk file name.).
![aim-upgrade-problem-01](https://cloud.githubusercontent.com/assets/2390009/11757109/6ad5b7d4-a024-11e5-96d0-35c2345a0ae8.JPG)
![aim-upgrade-problem-02](https://cloud.githubusercontent.com/assets/2390009/11757111/6ad9b06e-a024-11e5-9e32-876ef4df3bd2.JPG)
![aim-upgrade-problem-03](https://cloud.githubusercontent.com/assets/2390009/11757110/6ad8f4e4-a024-11e5-99f0-a925c1e5af58.JPG)
![aim-upgrade-problem-04](https://cloud.githubusercontent.com/assets/2390009/11757114/6ade7a40-a024-11e5-8e5f-1e4c70655b27.JPG)
![aim-upgrade-problem-05](https://cloud.githubusercontent.com/assets/2390009/11757113/6ade4afc-a024-11e5-82fd-6c095d902c91.JPG)
![aim-upgrade-problem-06](https://cloud.githubusercontent.com/assets/2390009/11757112/6add9e40-a024-11e5-8146-08ec4d97107a.JPG)
![aim-upgrade-problem-07](https://cloud.githubusercontent.com/assets/2390009/11757115/6ae3b46a-a024-11e5-9886-38e476d325c2.JPG)
![aim-upgrade-problem-08](https://cloud.githubusercontent.com/assets/2390009/11757116/6ae6bd9a-a024-11e5-8f8b-60d56d554040.JPG)
![aim-upgrade-problem-09](https://cloud.githubusercontent.com/assets/2390009/11757117/6aeac750-a024-11e5-8018-701100fe71d2.JPG)
![aim-upgrade-problem-10](https://cloud.githubusercontent.com/assets/2390009/11757118/6aedcb1c-a024-11e5-86b7-6d6239bf70be.JPG)
![aim-upgrade-problem-11](https://cloud.githubusercontent.com/assets/2390009/11757119/6aedca5e-a024-11e5-89e5-ef4102f96e23.JPG)
![aim-upgrade-problem-12](https://cloud.githubusercontent.com/assets/2390009/11757120/6aeef0fa-a024-11e5-831f-75c60f11dfd4.JPG)
![aim-upgrade-problem-13](https://cloud.githubusercontent.com/assets/2390009/11757121/6af42a34-a024-11e5-8ec3-5d6c55e0de69.JPG)

**Comment by pngbill** [comment]
Comments about images. There are 13 images and below is my commentary:

1. This image shows the choice for download at the https://build.phonegap.com/apps/713362/share site.
2. When I clicked on the Android option, the download started and this page popped up. It is rather confusing to figure out how to answer the question at the bottom of the page:

"This type of file can harm your device. Do you want to keep .AdaptitMobile-release.apk anyway?" [Cancel] [OK] [X]

 Clicking the [Cancel] or [X] just abort the download. I clicked [OK] to continue, even though it isn't really clear what the significance of keeping the .AdaptitMobile-release.apk is.
3. For "Complete action using" I clicked on the "Chrome" button, and "Just once".
4. This image shows the next question at the bottom of the screen: "Do you want to replace the existing .AdaptitMobile-release.apk in Download?" [CREATE NEW FILE] [REPLACE FILE] [X]. I clicked on [REPLACE FILE].
5. This screen says "Do you want to install an update to this existing application? Your existing data will not be lost. The updated application will get access to ... This update requires no new permissions. [Cancel] [Install]. I clicked on [Install].
6. This screen popped up almost immediately after I clicked on the [Install] button. It says X App not installed. [Done]. The only option is to click on [Done] which I did.
7. After trying the above process several times with the same result, I decided to go to the "Application Manager" in the Settings. Selecting Adapt It Mobile, it shows the App info. I scrolled down to make sure that there was no setting to clear out any previous data. I did not click on the "Clear data" button. But I just clicked on the "Uninstall" button. 
8. This image shows the prompt "Adapt It Mobile will be uninstalled." [Cancel] [Uninstall]. I clicked on [Uninstall]. The app installed successfully.
9. I went to my "Downloads" folder where the download for the new 0.5.0 version was located, and double clicked on the .apk file. This image shows the "Do you want to install this application? It will get access to: ... [Cancel] [Install]. I clicked on [Install].
10. This image shows the progress while installing.
11. This image shows "App installed." preceded by a check mark, and [Done] [Open] at the bottom. I clicked on [Open].
12. This image is the "Welcome to Adapt It Mobile" screen with [Continue]. I clicked on [Continue].
13. This image show the "Get Started" screen with the two options to "Create Project" and "Copy Project". This screen verified that the data from the previous installation was destroyed, and now the only option is to get started with a new project.

**Comment by eb1** [comment]
Looks like this might have been closed by mistake - reopening.

**Comment by eb1** [comment]
Not sure what happened to cause this issue, but it is from a fairly old build of AIM. Marking as closed.
