### ISSUE TITLE
AIM doesn't run on Android 5.1.1/Marshmallow

### ISSUE THREAD

**Issue by KLBradford** [adapt-it/adapt-it-mobile#137]
When starting the application (AIM 0.5.0 installed 1/13/2016) on a Nexus 5 phone running Android 5.1.1/Marshmallow, I receive the error message "Unfortunately, Adapt It Mobile has stopped", after which the application exits. This happens consistently, including after phone was restarted and after multiple uninstall/reinstalls.

Installation seemed to work fine, produced no errors.

**Comment by eb1** [comment]
Thanks!

Most of these errors are related to the Crosswalk plugin, which has been a mixed bag as far as its usefulness goes. Is this error due to some weird interaction with the Android OS level? Some incompatibility with the processor (Crosswalk separates the debug .apk into 2 -- one for x86 and another for ARM)? Hopefully we can isolate what's going on.

Nexus 5 is listed as having a Snapdragon 800 processor, which is an ARM-based processor.

**Comment by eb1** [comment]
@KLBradford - grasping at straws here... would it be possible to reinstall from https://build.phonegap.com/apps/713362/share on your device and retest?

There was a recent fix to the PhoneGap build that allows us to now use the latest crosswalk plugin from npm (instead of the plugin from a couple versions ago that's hosted on the PG build site). The updated build is on our share site above. It may or may not affect the inability of your device to run.

**Comment by KLBradford** [comment]
@eb1 Hmm... tried to install, but now I am getting the message "App did not install.". I uninstalled the app, cleared cache, and rebooted, still get that message and app won't install. I will keep trying - any ideas?

**Comment by eb1** [comment]
Ugh. It looks like the PhoneGap build folk haven't _really_ fixed their packaging issues. I tried a few permutations (older versions, etc.), but it doesn't install on my machine either, unless I remove crosswalk altogether. I'll shelve this issue for later investigation. Thanks for trying it out, though!

**Comment by eb1** [comment]
Okay, once more _with feeling_. :-) I've updated the code to remove crosswalk -- and the page transition animation it was meant to fix. Would it be possible to download from the same location (https://build.phonegap.com/apps/713362/share) and try it out again?

I've verified that it works on both my older phone and tablet. You might need to uninstall the current version in order to install this one.

**Comment by pngbill** [comment]
My Moto G Android phone is running Android 5.1. I tried just upgrading the previous AIM. The installation of the apk file seemed to work OK, and data appeared to be preserved for the upgrade. However, when I selected the last opened chapter to adapt, all I got was "Loading ... Please wait" and that message never ended. So I uninstalled the app, and then installed AIM afresh. The installation wiped out all my data :(, but I was able then to import the first chapter of Galatians, and open the file for adaptation. Hence, AIM appears to work OK on my 5.1 smartphone.

**Comment by eb1** [comment]
Okay, thanks for testing! This code change is currently in the 0.5.5 milestone; I've added this fix to the issue list.

Part of the necessary change here was to disable the page transition that prompted us to add Crosswalk to the mix in the first place (see: https://github.com/adapt-it/adapt-it-mobile/issues/73). Disabling this page transition does result in page transitions that aren't that pretty, but there's no rendering problem on older Android devices. I'll write up a separate lower-priority issue to go poke at the page transitions again -- there's got to be some transition that will work on older mobile browsers that we can use. 

We'll also need to keep an eye out for issues that having the default (older) browser could cause -- weird rendering, etc.
