### ISSUE TITLE
Unable to import large SFM files from Paratext

### ISSUE THREAD

**Issue by KLBradford** [adapt-it/adapt-it-mobile#138]
On tablet running Lollipop 5.1.1, I was unable to import Genesis SFM files taken directly from Paratext for the Koonzime language(ozm) from Cameroon. Trying to import the full book of Genesis ran 10 hours or more, after which I gave up (multiple times, same result). I tried just chapter 1, and got the error message “Import Failed: reason: undefined”. Files attached.

[01GENBadAllCH1.txt](https://github.com/adapt-it/adapt-it-mobile/files/90646/01GENBadAllCH1.txt)
[01GENBadAll.txt](https://github.com/adapt-it/adapt-it-mobile/files/90645/01GENBadAll.txt)

**Comment by eb1** [comment]
I'm thinking this issue might be memory related. On the desktop (Chrome), the full file takes less than 5 seconds to import, and chapter 1 is almost instantaneous. There are 50903 sourcephrase objects in the whole book, which are bulk inserted at the end of the import.

I'll try this file on a couple other devices I've got, to see if I can reproduce the issue.

**Comment by eb1** [comment]
Reproduced on Samsung Galaxy 3 phone (4.3):

- My Lenovo tablet (4.4.3) successfully imported both the 01GENBadALLCH1.txt and 01GENBadAdd.txt files.
- On the phone, I was able to import the 01GENBadALLCH1.txt file (and subsequently adapt the chapter), but when I attempted to import the file to my phone, it got stuck during the last phase. The status reads "file read. saving contents..." after about 20 seconds of doing the import, and gets stuck during the addBatch() call to insert the sourcePhrases into the database.

**Comment by eb1** [comment]
I think I've got a workable solution for this issue, but it'll need some testing and possibly some tuning to make sure it covers all the cases correctly.

In the import document code, AIM will now split the source phrase INSERT transactions into batches with a maximum size of MAX_BATCH (tunable in the code, and currently set to 10,000). I've run this on the 01GENBaddAll.txt file:

- The correct number of objects -- 50903 -- are created. These do appear to have the correct starting and ending words as well.
- The import now works on my older phone.

As this issue is memory related, I'm not sure if this initial batch size of 10,000 will work on all older phones. I would also like to verify this fix on other larger documents to make sure we've got a good solution in place here -- and that we're not losing any data.

**Comment by eb1** [comment]
Also of note -- this larger file does take some time to import on my older phone. I needed to wait between 30 seconds and 1 minute.

**Comment by adaptitbruce** [comment]
Hi Erik,  sounds quite acceptable. That's about 3 seconds per chapter - and that's pretty good! My wife fiddles with my Android 7" tablet (which I've not had time to use, she's taken it over), and she spends more time than that just finding out how to do basic things like get hooked in to the modem, or whatever. To get 50 large chapters in less than a minute? Not a problem.

--Bruce
  ----- Original Message -----
