### ISSUE TITLE
Parallel Scroll feature with Accordance

### ISSUE THREAD

**Issue by Berovowilare** [adapt-it/adapt-it-mobile#430]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Berovowilare** [comment]
Hello

Paratext, Bibledit have a scroll feature with Accordancebible.com, so if you go to a bible verse with one application the other goes the the same too. It is very handy if you have both application open. In the Bible software you can search and in the translation software... and both are always in sync.

**Comment by eb1** [comment]
I'm going to need more information on this enhancement request. Is this referring to the parallel scrolling between Paratext and other apps on the Windows desktop platform? (I.e., using Window messages and the Windows registry key ("HKEY_CURRENT_USER\\Software\\SantaFe\\Focus\\ScriptureReference")) to update other Windows apps of the location to scroll to -- or some other mechanism?

**Comment by Berovowilare** [comment]
Hello 

Yes on the Windows it is the SantaFe. Like Paratext also use. The HKEY... is Windows only.

On the Mac has Accordance with Bibledit found another way. I have this requested and Accordance found a solution. AFAIK it is based on the KJV verse mapping and it works on both ways. But you can use also other versifications. 
As Bibledit has this implemented in the Mac version I have also requested this too on the Logos forums. And I guess on the Logos feature request website. As Logos is the great competitor so they don't have to ask Accordance but they can get in contact with Bibledit. Paratext don't have a Mac version, so there is no need to ... 
The head of developers from at accordancebible.com is Joel. I guess you got it.

You can download the free version of Accordance for Mac on https://www.accordancebible.com/Accordance-Installers/.
Open Bibledit and activate the feature in Accordance in the preferences:
<img width="782" alt="Bildschirmfoto 2021-02-20 um 21 59 06" src="https://user-images.githubusercontent.com/36891575/108608489-78f5e880-73c7-11eb-9c96-32b43b265f3b.png">
Then you can see how it works.

**Comment by eb1** [comment]
Thanks for the clarification. :-) This repository is for the mobile app -- Adapt It Mobile, for Android/iOS.

For the desktop version (https://github.com/adapt-it/adaptit), I know that there is code to track the SantaFe scrolling mechanism on Windows. I don't know if it's been implemented on the Mac / Linux platforms, though. Let me check with the team, and possibly open an issue over there. Thanks again for reporting the issue!

**Comment by Berovowilare** [comment]
Sorry I don't know why I ended up in the wrong repository. I saw it as I wrote the answer.

**Comment by eb1** [comment]
No worries! I've sent an email to the group about non-Windows support for the parallel scrolling. We should be able to track it down soon. Thanks again for reaching out!

**Comment by eb1** [comment]
A couple updates on this issue:

- I've created an enhancement request over in the Adapt It repo to track this request.
- In talking with the developers of the cross-platform toolkit that Adapt It uses (wxWidgets), I found out that the class that the Accordance / Bibledit devs used for inter-process communication -- NSDistributedNotificationCenter -- is not implemented in the wxWidgets API. So we really can't implement this feature using the method that Accordance/Bibledit did on non-Windows platforms at the moment. :-( 

I'm going to mark this issue as closed/invalid over here. Updates / comments can be made over at the new Adapt It desktop issue here: https://github.com/adapt-it/adaptit/issues/61. If it turns out that the wxWidgets devs decide to implement / support the NSDistributedNotifcationCenter API, we can reopen and re-evaluate the feature. Again, thanks for bringing this to our attention -- and so sorry we "can't get there from here" right now!
