### ISSUE TITLE
Support multiple refstring entries in KB

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#85]
Currently when there is more than one entry for a particular source phrase in AIM's knowledge base, AIM will just pick the first entry and move on to the next pile. We need to support the possibility of more than one adaptation value for a source phrase -- maybe through a drop-down list?

**Comment by adaptitbruce** [comment]
Hi Erik,
Whatever you do, it needs to be easily possible for the user to reject all the entries being shown to him, and instead type a new adaptation that isn't one of the current set of possibilities. This need happens often enough that it needs to be as easy to do as choosing any one of the listed adaptations. (Icing on the cake would be to also provide a "Cancel and Select" option like in AID -- that is, none of the options are wanted, and a new entry at that one pile isn't wanted either, what *is* wanted is that that pile is the first in a merger which needs to commence there - so select that pile and the next and let the user extent the selection further if more than two words are to be in the merger. This too is an often wanted situation, though it can be achieved in AID by a sequence of actions - such as cancelling the dialog, and manually making the selection. (AID also allows the ALT+right arrow, which is typically how one extends the selection to the right, to act within the dialog as equivalent to the press of the "Cancel and Select" button - so that the one key combination can be given for both cancelling the dialog, selecting the first two words, and extending the selection further.) Dunno now much of that kind of functionality is attainable in AIM.

--Bruce
  ----- Original Message ----- 
  From: Erik Brommers 
  To: adapt-it/adapt-it-mobile 
  Sent: Friday, July 03, 2015 7:43 AM
  Subject: [adapt-it-mobile] Support multiple refstring entries in KB (#85)


  Currently when there is more than one entry for a particular source phrase in AIM's knowledge base, AIM will just pick the first entry and move on to the next pile. We need to support the possibility of more than one adaptation value for a source phrase -- maybe through a drop-down list?

**Comment by pngbill** [comment]
I know that Android (and I believe that IOS) devices have "auto-correction" or "word-completion" that are often activated by default. When working in AIM with a non-English target text, these features should be turned off to avoid auto-correcting/word-completion of vernacular words into English or whatever major dictionary is loaded. Turning these features off can save precious screen space above the keyboard on small screen devices. On the other hand, if the word-completion feature could be harnessed to display translation equivalents from AIM's KB, it might be an ideal way to allow for easy selection of translation equivalents by the user without having to display a drop-down list or popup dialog with a list.

**Comment by eb1** [comment]
Looks like this is working. The drop-down uses the Twitter Typeahead library to display the list of entries found in the KB; the user can either select one from the list or type in another translation for the sourcephrase.
