### ISSUE TITLE
Unreadable screen after changing orientation - Create Project language

### ISSUE THREAD

**Issue by eb1** [adapt-it/adapt-it-mobile#90]
Alpha (0.3 milestone) input from Jonathan, run on a rooted Samsung S4, Android 4.4.4:

I was able to confuse it by switching phone orientation at the create project language input screen, the screen went unreadable, but switching orientation back and forth cleaned it up.  Not sure I can duplicate this, will try some more later.

**Comment by eb1** [comment]
This could be related to issue #73 -- which appears to be a browser rendering bug on Android. 

On my Lenovo tablet (Android 4.4.2), I'm noticing some weirdness with the project language screen appearing mostly offscreen, similar to what's happening on the Search screen on Android. Switching the orientation back and forth refreshes the display properly, as does clicking on the screen.

**Comment by gateslp** [comment]
Hi Erik,

I had this issue or similar on jellybean 4.1.1 & 4.1.2 on an aldi Bauhn 10"
tablet & got sick of it & ended up coding to stop rotation & screen
changes. I took this approach after I saw a few apps I had previously
downloaded adopting this sort of orientation. I read where those coders did
that to avoid having to re-orient/re-scale photo images captured from the
camera or from a browser, since re-rendering was constrained by having to
alter data-entry fields to cater for this re-orientation.

That last bit was my excuse anyway.

On the lenovo 7" model Bruce & I got , I've upgraded to android 5 , perhaps
this quirk is addressed ? I'd like to try out the app on this tablet ... ok
with you ?

regards,

**Comment by gateslp** [comment]
On the lenovo 7" model Bruce & I got , I've upgraded to android 5 , perhaps this quirk is addressed ? I'd like to try out the app on this tablet ... ok with you ?

**Comment by eb1** [comment]
Thanks for testing this -- and confirming that it's no longer there on Android 5! That pretty much confirms that it's a rendering issue that's fixed in later Android browsers, like the one we're seeing in issue #73.

We'll still need to address the issue for older versions of Android, since it does have a slice of market share (and is more likely to be found in developing markets). I'll leave this issue open until we can figure out a broader solution. Thanks again!

**Comment by gateslp** [comment]
Hi Erik,

Perhaps I wasn't clear ... I have not yet downloaded the package to test it
... is it on github for me to grab ?

regards,

**Comment by eb1** [comment]
Marking this issue as resolved:

- PhoneGap Build build now supports the crosswalk browser plugin; I've added this plugin to the config.xml file so that our builds now include it for the Android browser.
- With the inclusion of the crosswalk browser, the rendering bug causing this issue no longer occurs on my Lenovo tablet (Android 4.4.2).
- For local builds, Bill found that the "use host GPU" setting needs to be enabled in the emulator for this to work properly. He's added it to the setup script for linux.

**Comment by kanaka** [comment]
I helped @pngbill debug his Android emulation issue this weekend to track down the host GPU issue. The problem was that crosswalk requires a certain level of GPU acceleration. According to [this](https://crosswalk-project.org/documentation/about/faq.html), crosswalk only supports Android 4.0+. Out of curiosity, what Android versions does AIM intend to support?

**Comment by eb1** [comment]
At the moment, Android 4.0+. It does look like the % of devices in use in 2015 (i.e., checking into the Google Play store) with a version < 4.0 is at less than 5%.

Source: https://developer.android.com/about/dashboards/index.html
